# Generated by Django 2.2.14 on 2020-08-05 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('binding', models.BooleanField(choices=[(0, '精装'), (1, '简装')])),
                ('publisher', models.CharField(max_length=100)),
                ('pubdate', models.DateField()),
                ('price', models.FloatField()),
                ('pages', models.IntegerField()),
                ('isbn', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m')),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
