# Generated by Django 2.2.14 on 2020-08-05 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launched', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('bidw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('uidw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wish',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launched', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('bidg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('uidg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gift',
            },
        ),
    ]
