# Generated by Django 2.2.14 on 2020-08-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_gift_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=256)),
                ('message', models.CharField(max_length=256)),
                ('mobile', models.CharField(max_length=16)),
                ('isbn', models.CharField(max_length=32)),
                ('book_title', models.CharField(max_length=64)),
                ('book_author', models.CharField(max_length=64)),
                ('book_img', models.ImageField(upload_to='driftbook/%Y/%m')),
                ('requester_id', models.IntegerField()),
                ('requester_nickname', models.CharField(max_length=32)),
                ('gifter_id', models.IntegerField()),
                ('gift_id', models.IntegerField()),
                ('gifter_nickname', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drift',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='wish',
            options={'ordering': ['-id']},
        ),
    ]
