# Generated by Django 2.2.14 on 2020-08-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='nickname',
        ),
    ]
